name: Sync Fork with v-2 Branch

on:
  schedule:
    - cron: '*/30 * * * *' # This schedules the workflow to run every 30 minutes. Adjust as needed.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Configure Git
        run: |
          git config user.name "jacobcoro"
          git config user.email "xiaokourou@gmail.com"

      - name: Sync with Upstream's v-2 Branch
        run: |
          git remote add upstream https://github.com/original-owner/original-repository.git
          git fetch upstream
          git checkout main
          git merge upstream/v-2
          git push
