name: Sync Fork with Upstream Branch

on:
  schedule:
    - cron: '*/30 * * * *' # This schedules the workflow to run every 30 minutes. Adjust as needed.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Updated to v3 for Node.js 20 support
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
          token: ${{ secrets.WORKFLOW_TOKEN }}  # Ensures you have a token for operations

      - name: Configure Git
        run: |
          git config user.name "jacobcoro"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with Upstream's main Branch
        run: |
          git remote add upstream https://github.com/eweser/eweser-db.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push
